/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tpglproj;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author pc
 */
public class AGENT_Vente extends javax.swing.JFrame {
  String queryG="SELECT * FROM products;";
    /**
     * Creates new form 
     */
    public AGENT_Vente() throws SQLException, ClassNotFoundException {
        initComponents();
        Table(queryG);
       JTableHeader head = jTable1.getTableHeader();
       TableColumnModel col = jTable1.getColumnModel();
        JScrollPane scrollPane = new JScrollPane();
        jTable1.getTableHeader().setFont(new Font("sansserif",Font.BOLD,14));
         jTable1.getTableHeader().setBackground(Color.WHITE); //Does its job
        jTable1.getTableHeader().setBackground(scrollPane.getBackground());
        jTable1.getTableHeader().setOpaque(true);
             
                  jTable1.getTableHeader().setForeground(new Color(0,0,0));
                       jTable1.setRowHeight(35);
                       
    }
    public AGENT_Vente(String name){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Stockpage = new javax.swing.JPanel();
        productpage = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        newProduct = new javax.swing.JButton();
        DeleteProduct = new javax.swing.JButton();
        ModifyProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        productbutton = new javax.swing.JLabel();
        clientbutton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Stockpage.setBackground(new java.awt.Color(114, 9, 183));
        Stockpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Stockpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        productpage.setBackground(new java.awt.Color(114, 9, 183));

        searchInput.setBackground(new java.awt.Color(255, 255, 255));
        searchInput.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        searchInput.setText("Search by reference | by designation");
        searchInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchInputFocusLost(evt);
            }
        });
        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 155, 183));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By Reference", "By designation" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(86, 11, 173));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\search (2).png")); // NOI18N
        jButton1.setText("     Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 255, 251));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        newProduct.setBackground(new java.awt.Color(45, 0, 225));
        newProduct.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        newProduct.setForeground(new java.awt.Color(255, 255, 255));
        newProduct.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\plus (1).png")); // NOI18N
        newProduct.setText("    New product");
        newProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductActionPerformed(evt);
            }
        });

        DeleteProduct.setBackground(new java.awt.Color(154, 3, 30));
        DeleteProduct.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        DeleteProduct.setForeground(new java.awt.Color(255, 255, 255));
        DeleteProduct.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Downloads\\minus.png")); // NOI18N
        DeleteProduct.setText("    Delete product");
        DeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductActionPerformed(evt);
            }
        });

        ModifyProduct.setBackground(new java.awt.Color(0, 114, 0));
        ModifyProduct.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        ModifyProduct.setForeground(new java.awt.Color(255, 255, 255));
        ModifyProduct.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\document.png")); // NOI18N
        ModifyProduct.setText("   Modify product");
        ModifyProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyProductActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\gl images\\refresh.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout productpageLayout = new javax.swing.GroupLayout(productpage);
        productpage.setLayout(productpageLayout);
        productpageLayout.setHorizontalGroup(
            productpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(productpageLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(productpageLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(newProduct)
                .addGap(18, 18, 18)
                .addComponent(ModifyProduct)
                .addGap(18, 18, 18)
                .addComponent(DeleteProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );
        productpageLayout.setVerticalGroup(
            productpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productpageLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(productpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addGroup(productpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(productpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ModifyProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(productpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 870, 650));

        jPanel3.setBackground(new java.awt.Color(86, 11, 173));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Downloads\\milk.png")); // NOI18N
        jLabel3.setText("MilkyWay");

        productbutton.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        productbutton.setForeground(new java.awt.Color(255, 255, 255));
        productbutton.setText("Manage products");
        productbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productbuttonMouseClicked(evt);
            }
        });

        clientbutton.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        clientbutton.setForeground(new java.awt.Color(255, 255, 255));
        clientbutton.setText("Manage clients");
        clientbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(productbutton)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(62, 62, 62)
                .addComponent(productbutton)
                .addGap(49, 49, 49)
                .addComponent(clientbutton)
                .addContainerGap(432, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
           
            String searchedItem= searchInput.getText();
            String searchtype =(String) jComboBox1.getSelectedItem();
            Connect conic = new Connect();
            Connection cnx = conic.connect();
            Statement st= (Statement) cnx.createStatement();
            String query1="";
            System.out.println("connected!");
            if(searchtype.compareTo("By Reference")==0){
                System.out.println(searchtype);
                query1 = "SELECT * FROM products WHERE reference='"+searchedItem+"';";
                System.out.println(query1);
            }else{
                query1 = "SELECT * FROM products WHERE designation='"+searchedItem+"';";
            }
            
            
            Table(query1);
            ResultSet res = st.executeQuery(query1);
            
            
           if(res.next()){
                System.out.println("ok");
                System.err.println(res.getFloat("weight"));
                
                
                
            }else{
                System.out.println("rip");
            }
            
            
            cnx.close();
        } catch (SQLException ex) {
            Logger.getLogger(AGENT_Vente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AGENT_Vente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void clientbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientbuttonMouseClicked
        // TODO add your handling code here:
        productpage.setVisible(false);
        Stockpage.setVisible(true);
    }//GEN-LAST:event_clientbuttonMouseClicked

    private void productbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productbuttonMouseClicked
        // TODO add your handling code here:
        productpage.setVisible(true);
        Stockpage.setVisible(false);
    }//GEN-LAST:event_productbuttonMouseClicked

    private void newProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductActionPerformed
        // TODO add your handling code here:
        
        new AddProduct().setVisible(true);
        
    }//GEN-LAST:event_newProductActionPerformed

    private void DeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         
        int option= JOptionPane.showConfirmDialog(null, "Are you sure you want to delete Product "+model.getValueAt(jTable1.getSelectedRow(), 0).toString()+" ", "Delete Product", JOptionPane.YES_NO_OPTION);
        if(option==0){
       if(jTable1.getSelectedRowCount()==1){
           try {
               String id =(String) model.getValueAt(jTable1.getSelectedRow(), 0);
               model.removeRow(jTable1.getSelectedRow());
               Connect conic = new Connect();
               Connection cnx = conic.connect();
               PreparedStatement st= (PreparedStatement) cnx.prepareStatement("DELETE FROM products where reference='"+id+"';");
               st.executeUpdate();
               System.out.println(id);
               cnx.close();
           } catch (SQLException ex) {
               Logger.getLogger(AGENT_Vente.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(AGENT_Vente.class.getName()).log(Level.SEVERE, null, ex);
           }
       }else{
           JOptionPane.showMessageDialog(null, "no selected row");
       }
        }
    }//GEN-LAST:event_DeleteProductActionPerformed

    private void searchInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInputFocusGained
        // TODO add your handling code here:
        
        searchInput.setText(null);
        searchInput.setForeground(Color.black);
    }//GEN-LAST:event_searchInputFocusGained

    private void searchInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInputFocusLost
        // TODO add your handling code here:
        if(searchInput.getText()==null){
            
        searchInput.setText("Search by Refence | by Designation");
        searchInput.setForeground(Color.gray);
        }
    }//GEN-LAST:event_searchInputFocusLost

    private void ModifyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyProductActionPerformed
        if(jTable1.getSelectedRowCount()==1){
        try {
          // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
          String id =(String) model.getValueAt(jTable1.getSelectedRow(), 0);
          new ModifyProduct(id).setVisible(true);
      } catch (ParseException ex) {
          Logger.getLogger(AGENT_Vente.class.getName()).log(Level.SEVERE, null, ex);
      }
        }else{
            JOptionPane.showMessageDialog(null, "NO ROW SELECTED!");
        }
      
    }//GEN-LAST:event_ModifyProductActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      try {
          // TODO add your handling code here:
          Table(queryG);
      } catch (SQLException ex) {
          Logger.getLogger(AGENT_Vente.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(AGENT_Vente.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jLabel1MouseClicked

        public void Table(String query) throws SQLException, ClassNotFoundException {
     
        
         
         String[] columns = {"reference","designation","type","weight","nutrition_val","production_date","premption_date","ingredients"};
       
    Connect conic = new Connect();
            Connection cnx = conic.connect();
            Statement st= (Statement) cnx.createStatement();
          
             ResultSet res = st.executeQuery(query);
            System.out.println("connected!");
            DefaultTableModel model = new DefaultTableModel(null,columns);
            Object[] afficher=new Object[8];
        while(res.next()){
            afficher[0]=res.getString("reference") ;
        afficher[1]=res.getString("designation");
        afficher[2]=res.getString("type");
        afficher[3]=res.getString("weight");
        afficher[4]=res.getString("nutrition_val");
        afficher[5]=res.getString("production_date");
        afficher[6]=res.getString("premption_date");
        afficher[7]=res.getString("ingredients");
        
        model.addRow(afficher);
        }
            
            
       
           
        model.addRow(afficher);
        jTable1.setModel(model);
        cnx.close();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AGENT_Vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AGENT_Vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AGENT_Vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AGENT_Vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AGENT_Vente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AGENT_Vente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AGENT_Vente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteProduct;
    private javax.swing.JButton ModifyProduct;
    private javax.swing.JPanel Stockpage;
    private javax.swing.JLabel clientbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton newProduct;
    private javax.swing.JLabel productbutton;
    private javax.swing.JPanel productpage;
    private javax.swing.JTextField searchInput;
    // End of variables declaration//GEN-END:variables
}
